package main

/*
	此文件主要放置通用配置、通用函数以及全局变量
*/

const (
	// FakeHeader for when web sites checke request header
	FakeHeader = `
	"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Charset": "UTF-8,*;q=0.5",
    "Accept-Encoding": "gzip,deflate,sdch",
    "Accept-Language": "en-US,en;q=0.8",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"`
)

var (
	// MediaTypeMap -
	MediaTypeMap = map[string]string{
		"video/3gpp":      "3gp",
		"video/f4v":       "flv",
		"video/mp4":       "mp4",
		"video/MP2T":      "ts",
		"video/quicktime": "mov",
		"video/webm":      "webm",
		"video/x-flv":     "flv",
		"video/x-ms-asf":  "asf",
		"audio/mp4":       "mp4",
		"audio/mpeg":      "mp3",
		"audio/wav":       "wav",
		"audio/x-wav":     "wav",
		"audio/wave":      "wav",
		"image/jpeg":      "jpg",
		"image/png":       "png",
		"image/gif":       "gif",
		"application/pdf": "pdf",
	}

	// SitesMap -
	SitesMap = map[string]string{
		"163":              "netease",
		"56":               "w56",
		"acfun":            "acfun",
		"archive":          "archive",
		"baidu":            "baidu",
		"bandcamp":         "bandcamp",
		"baomihua":         "baomihua",
		"bigthink":         "bigthink",
		"bilibili":         "bilibili",
		"cctv":             "cntv",
		"cntv":             "cntv",
		"cbs":              "cbs",
		"coub":             "coub",
		"dailymotion":      "dailymotion",
		"dilidili":         "dilidili",
		"douban":           "douban",
		"douyu":            "douyutv",
		"ehow":             "ehow",
		"facebook":         "facebook",
		"fantasy":          "fantasy",
		"fc2":              "fc2video",
		"flickr":           "flickr",
		"freesound":        "freesound",
		"fun":              "funshion",
		"google":           "google",
		"giphy":            "giphy",
		"heavy-music":      "heavymusic",
		"huaban":           "huaban",
		"huomao":           "huomaotv",
		"iask":             "sina",
		"icourses":         "icourses",
		"ifeng":            "ifeng",
		"imgur":            "imgur",
		"in":               "alive",
		"infoq":            "infoq",
		"instagram":        "instagram",
		"interest":         "interest",
		"iqilu":            "iqilu",
		"iqiyi":            "iqiyi",
		"isuntv":           "suntv",
		"joy":              "joy",
		"kankanews":        "bilibili",
		"khanacademy":      "khan",
		"ku6":              "ku6",
		"kugou":            "kugou",
		"kuwo":             "kuwo",
		"le":               "le",
		"letv":             "le",
		"lizhi":            "lizhi",
		"magisto":          "magisto",
		"metacafe":         "metacafe",
		"mgtv":             "mgtv",
		"miomio":           "miomio",
		"mixcloud":         "mixcloud",
		"mtv81":            "mtv81",
		"musicplayon":      "musicplayon",
		"naver":            "naver",
		"7gogo":            "nanagogo",
		"nicovideo":        "nicovideo",
		"panda":            "panda",
		"pinterest":        "pinterest",
		"pixnet":           "pixnet",
		"pptv":             "pptv",
		"qingting":         "qingting",
		"qq":               "qq",
		"quanmin":          "quanmin",
		"showroom-live":    "showroom",
		"sina":             "sina",
		"smgbb":            "bilibili",
		"sohu":             "sohu",
		"soundcloud":       "soundcloud",
		"ted":              "ted",
		"theplatform":      "theplatform",
		"tucao":            "tucao",
		"tudou":            "tudou",
		"tumblr":           "tumblr",
		"twimg":            "twitter",
		"twitter":          "twitter",
		"ucas":             "ucas",
		"videomega":        "videomega",
		"vidto":            "vidto",
		"vimeo":            "vimeo",
		"wanmen":           "wanmen",
		"weibo":            "miaopai",
		"veoh":             "veoh",
		"vine":             "vine",
		"vk":               "vk",
		"xiami":            "xiami",
		"xiaokaxiu":        "yixia",
		"xiaojiadianvideo": "fc2video",
		"ximalaya":         "ximalaya",
		"yinyuetai":        "yinyuetai",
		"miaopai":          "yixia",
		"yizhibo":          "yizhibo",
		"youku":            "youku",
		"iwara":            "iwara",
		"youtu":            "youtube",
		"youtube":          "youtube",
		"zhanqi":           "zhanqi",
		"365yg":            "toutiao",
	}
)
